### ISSUE TITLE
Failed to load entry point 'doctor'

### ISSUE THREAD

**Issue by razr** [Wind-River/vxworks7-ros2-build#84]
[vxWorks *]# python3 ros2 doctor
Launching process 'python3' ...
Process 'python3' (process Id = 0xffff800000362be0) launched.
Failed to load entry point 'doctor': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.21.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: Shared object "libc.so.6" not found Or Cannot stat "libc.so.6" Or "libc.so.6" is not a regular file

Traceback (most recent call last):
  File "/ata4/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.7', 'console_scripts', 'ros2')())
  File "/usr/lib/python3.9/site-packages/ros2cli/cli.py", line 50, in main
    add_subparsers_on_demand(
  File "/usr/lib/python3.9/site-packages/ros2cli/command/__init__.py", line 237, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'doctor'

**Comment by razr** [comment]
the default gateway is missing in the command line options `g=192.168.200.254`. Thanks @robwoolley for point it out.

**Comment by razr** [comment]
#86 partially fix `python3 ros2 doctor`
